import os

# Setup local build environment and paths
Import('env')
local_env = env.Clone()
root = os.path.dirname(Dir('.').srcnode().abspath)
media_path = os.path.join(root, 'media')
common_path = os.path.join(root, 'common')

# Build Document
local_env.PrependENVPath('PATH', common_path)
local_env.Append(TEXINPUTS=[common_path, media_path])
pdf = local_env.PDF('document.tex')
if env['VARIANT']:
    install = local_env.InstallAs(
        'Introduction to Robotframework - Kenneth E. Bellock.pdf', pdf)
    Return('install')
